INSERT INTO `bc_category` VALUES('1','1','content','0','1','0','0','1','1,7,8,9,17,18,19,20,21,23,24,22,25,26','关于英诺特','','','','','about','/index.php?m=content&c=index&a=lists&catid=1','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','guanyuyingnuote','');
INSERT INTO `bc_category` VALUES('2','1','content','0','2','0','0','1','2,28,29,30,31','新闻动态','','','','','news','/news/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','2','1','0','xinwendongtai','');
INSERT INTO `bc_category` VALUES('3','1','content','0','30','0','0','1','3,71,73,74,92,93,94,95,96,97,72,75,76,77','产品','','','','','product','/product/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','3','1','0','chanpin','');
INSERT INTO `bc_category` VALUES('4','1','content','0','1','0','0','1','4,27,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54','解决方案','','','','','solution','/solution/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','4','1','0','jiejuefangan','');
INSERT INTO `bc_category` VALUES('5','1','content','0','1','0','0','1','5,55,56,57,58,59,60,61,62,63,64,65','服务与支持','','','','','support','/index.php?m=content&c=index&a=lists&catid=5','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','5','1','0','fuwuyuzhichi','');
INSERT INTO `bc_category` VALUES('6','1','content','0','1','0','0','1','6,66,67,68,69,70','加入我们','','','','','join','/join/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','6','1','0','jiaruwomen','');
INSERT INTO `bc_category` VALUES('7','1','content','0','1','1','0,1','1','7,8,9','公司简介','','/uploadfile/2021/1129/20211129120729888.png','','about/','gsjs','/about/gsjs/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_about\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','1','1','0','gongsijianjie','');
INSERT INTO `bc_category` VALUES('8','1','content','0','1','7','0,1,7','0','8','相册管理','','/uploadfile/2021/1129/20211129120729888.png','','about/gsjs/','picgl','/index.php?m=content&c=index&a=lists&catid=8','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','xiangceguanli','');
INSERT INTO `bc_category` VALUES('9','1','content','0','1','7','0,1,7','0','9','内容介绍','','/uploadfile/2021/1129/20211129120729888.png','','about/gsjs/','nrgl','/index.php?m=content&c=index&a=lists&catid=9','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','neirongjieshao','');
INSERT INTO `bc_category` VALUES('10','1','content','0','1','0','0','1','10,11,12,13,14,15,16','栏目banner','','','','','lmbanner','/index.php?m=content&c=index&a=lists&catid=10','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','10','0','0','lanmubanner','');
INSERT INTO `bc_category` VALUES('11','1','content','0','1','10','0,10','0','11','关于英诺特','','','','lmbanner/','gyban','/index.php?m=content&c=index&a=lists&catid=11','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','11','1','0','guanyuyingnuote','');
INSERT INTO `bc_category` VALUES('12','1','content','0','1','10','0,10','0','12','新闻动态','','','','lmbanner/','xwdtb','/index.php?m=content&c=index&a=lists&catid=12','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','12','1','0','xinwendongtai','');
INSERT INTO `bc_category` VALUES('13','1','content','0','1','10','0,10','0','13','产品','','','','lmbanner/','cpba','/index.php?m=content&c=index&a=lists&catid=13','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','13','1','0','chanpin','');
INSERT INTO `bc_category` VALUES('14','1','content','0','1','10','0,10','0','14','解决方案','','','','lmbanner/','jjfab','/index.php?m=content&c=index&a=lists&catid=14','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','14','1','0','jiejuefangan','');
INSERT INTO `bc_category` VALUES('15','1','content','0','1','10','0,10','0','15','服务与支持','','','','lmbanner/','fwyzcb','/index.php?m=content&c=index&a=lists&catid=15','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','15','1','0','fuwuyuzhichi','');
INSERT INTO `bc_category` VALUES('16','1','content','0','1','10','0,10','0','16','加入我们','','','','lmbanner/','jrwmb','/index.php?m=content&c=index&a=lists&catid=16','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','16','1','0','jiaruwomen','');
INSERT INTO `bc_category` VALUES('17','1','content','0','1','1','0,1','0','17','发展历程','','/uploadfile/2021/1129/20211129054105208.png','','about/','fzlc','/about/fzlc/','7','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_about_fzlc\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','2','1','0','fazhanlicheng','');
INSERT INTO `bc_category` VALUES('18','1','content','0','1','1','0,1','0','18','荣誉资质','','/uploadfile/2021/1129/20211129064523535.png','','about/','honor','/about/honor/','5','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_about_honor\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','3','1','0','rongyuzizhi','');
INSERT INTO `bc_category` VALUES('19','1','content','0','1','1','0,1','0','19','企业文化','','/uploadfile/2021/1129/20211129065728610.png','','about/','Culture','/about/Culture/','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_about_culture\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','4','1','0','qiyewenhua','');
INSERT INTO `bc_category` VALUES('20','1','content','0','1','1','0,1','1','20,21,23,24,22,25,26','联系我们','','/uploadfile/2021/1129/20211129071740989.png','','about/','contact','/about/contact/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_about_contact\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','5','1','0','lianxiwomen','');
INSERT INTO `bc_category` VALUES('21','1','content','0','1','20','0,1,20','1','21,23,24','北京','','/uploadfile/2021/1129/20211129071740989.png','','about/contact/','bj','/index.php?m=content&c=index&a=lists&catid=21','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','beijing','');
INSERT INTO `bc_category` VALUES('22','1','content','0','1','20','0,1,20','1','22,25,26','唐山','','/uploadfile/2021/1129/20211129071740989.png','','about/contact/','ts','/index.php?m=content&c=index&a=lists&catid=22','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','tangshan','');
INSERT INTO `bc_category` VALUES('23','1','content','0','1','21','0,1,20,21','0','23','公司名称','','/uploadfile/2021/1129/20211129071740989.png','','about/contact/bj/','gsmc','/index.php?m=content&c=index&a=lists&catid=23','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','gongsimingcheng','');
INSERT INTO `bc_category` VALUES('24','1','content','0','1','21','0,1,20,21','0','24','详细信息','','/uploadfile/2021/1129/20211129071740989.png','','about/contact/bj/','xxdz','/index.php?m=content&c=index&a=lists&catid=24','5','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','xiangxixinxi','');
INSERT INTO `bc_category` VALUES('25','1','content','0','1','22','0,1,20,22','0','25','公司名称','','/uploadfile/2021/1129/20211129071740989.png','','about/contact/ts/','gsmc','/index.php?m=content&c=index&a=lists&catid=25','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','gongsimingcheng','');
INSERT INTO `bc_category` VALUES('26','1','content','0','1','22','0,1,20,22','0','26','详细信息','','/uploadfile/2021/1129/20211129071740989.png','','about/contact/ts/','xxxx','/index.php?m=content&c=index&a=lists&catid=26','5','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','xiangxixinxi','');
INSERT INTO `bc_category` VALUES('27','1','content','0','1','4','0,4','1','27,32,33,34','新冠病毒检测','','/uploadfile/2021/1129/20211129074831392.png','','solution/','xgbd','/solution/xgbd/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_solution\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','27','1','0','xinguanbingdujiance','');
INSERT INTO `bc_category` VALUES('28','1','content','0','2','2','0,2','0','28','公司新闻','','/uploadfile/2021/1129/20211129081711628.png','','news/','gsxw','/news/gsxw/','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_news\',
  \'show_template\' => \'show_news\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','28','1','0','gongsixinwen','');
INSERT INTO `bc_category` VALUES('29','1','content','0','2','2','0,2','0','29','行业动态','','/uploadfile/2021/1129/20211129084515455.png','','news/','hydt','/news/hydt/','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_news_hy\',
  \'show_template\' => \'show_news\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','29','1','0','xingyedongtai','');
INSERT INTO `bc_category` VALUES('30','1','content','0','2','2','0,2','0','30','活动专题','','/uploadfile/2021/1129/20211129103704873.png','','news/','hdzt','/news/hdzt/','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_news_zt\',
  \'show_template\' => \'show_news\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','30','1','0','huodongzhuanti','');
INSERT INTO `bc_category` VALUES('31','1','content','0','2','2','0,2','0','31','视频','','/uploadfile/2021/1129/20211129104313980.png','','news/','video','/news/video/','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_news_video\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','31','1','0','shipin','');
INSERT INTO `bc_category` VALUES('32','1','content','0','1','27','0,4,27','0','32','方案介绍','','/uploadfile/2021/1129/20211129074831392.png','','solution/xgbd/','fzjs','/index.php?m=content&c=index&a=lists&catid=32','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','fanganjieshao','');
INSERT INTO `bc_category` VALUES('33','1','content','0','1','27','0,4,27','0','33','图片说明','','/uploadfile/2021/1129/20211129074831392.png','','solution/xgbd/','tpsm','/index.php?m=content&c=index&a=lists&catid=33','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','tupianshuoming','');
INSERT INTO `bc_category` VALUES('34','1','content','0','1','27','0,4,27','0','34','检测项目','','/uploadfile/2021/1129/20211129074831392.png','','solution/xgbd/','jcxm','/index.php?m=content&c=index&a=lists&catid=34','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','jiancexiangmu','');
INSERT INTO `bc_category` VALUES('35','1','content','0','1','4','0,4','1','35,36,37,38','呼吸道感染病','','/uploadfile/2021/1130/20211130121419888.png','','solution/','hxdgr','/solution/hxdgr/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_solution_biao\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','35','1','0','huxidaoganranbing','');
INSERT INTO `bc_category` VALUES('36','1','content','0','1','35','0,4,35','0','36','方案介绍','','','','solution/hxdgr/','fajs','/index.php?m=content&c=index&a=lists&catid=36','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','fanganjieshao','');
INSERT INTO `bc_category` VALUES('37','1','content','0','1','35','0,4,35','0','37','图片说明','','','','solution/hxdgr/','tpsm','/index.php?m=content&c=index&a=lists&catid=37','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','tupianshuoming','');
INSERT INTO `bc_category` VALUES('92','1','content','0','30','71','0,3,71','0','92','胶体金-肝炎','','/uploadfile/2021/1202/20211202064510331.png','','product/platform/','gy','/product/platform/gy/','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','3','1','0','jiaotijin-ganyan','');
INSERT INTO `bc_category` VALUES('38','1','content','0','22','35','0,4,35','0','38','检测项目','','','','solution/hxdgr/','jcxm','/index.php?m=content&c=index&a=lists&catid=38','19','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','jiancexiangmu','');
INSERT INTO `bc_category` VALUES('39','1','content','0','1','4','0,4','1','39,40,41,42','优生优育检测','','/uploadfile/2021/1130/20211130033414141.png','','solution/','ysyy','/solution/ysyy/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_solution_biao\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','39','1','0','youshengyouyujiance','');
INSERT INTO `bc_category` VALUES('40','1','content','0','1','39','0,4,39','0','40','方案介绍','','/uploadfile/2021/1130/20211130033414141.png','','solution/ysyy/','fajs','/index.php?m=content&c=index&a=lists&catid=40','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','fanganjieshao','');
INSERT INTO `bc_category` VALUES('41','1','content','0','1','39','0,4,39','0','41','图片说明','','/uploadfile/2021/1130/20211130033414141.png','','solution/ysyy/','tpsm','/index.php?m=content&c=index&a=lists&catid=41','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','tupianshuoming','');
INSERT INTO `bc_category` VALUES('42','1','content','0','22','39','0,4,39','0','42','检测项目','','/uploadfile/2021/1130/20211130033414141.png','','solution/ysyy/','jcxm','/index.php?m=content&c=index&a=lists&catid=42','22','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','jiancexiangmu','');
INSERT INTO `bc_category` VALUES('43','1','content','0','22','4','0,4','1','43,44,45,46','优生备孕检测','','/uploadfile/2021/1130/20211130034004130.png','','solution/','ysby','/solution/ysby/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_solution_biao\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','43','1','0','youshengbeiyunjiance','');
INSERT INTO `bc_category` VALUES('44','1','content','0','1','43','0,4,43','0','44','方案介绍','','/uploadfile/2021/1130/20211130034004130.png','','solution/ysby/','fajs','/index.php?m=content&c=index&a=lists&catid=44','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','fanganjieshao','');
INSERT INTO `bc_category` VALUES('45','1','content','0','1','43','0,4,43','0','45','图片说明','','/uploadfile/2021/1130/20211130034004130.png','','solution/ysby/','tpsm','/index.php?m=content&c=index&a=lists&catid=45','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','tupianshuoming','');
INSERT INTO `bc_category` VALUES('46','1','content','0','22','43','0,4,43','0','46','检测项目','','/uploadfile/2021/1130/20211130034004130.png','','solution/ysby/','jcxm','/index.php?m=content&c=index&a=lists&catid=46','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','jiancexiangmu','');
INSERT INTO `bc_category` VALUES('47','1','content','0','1','4','0,4','1','47,48,49,50','肝炎病毒检测','','/uploadfile/2021/1130/20211130053620115.png','','solution/','gybd','/solution/gybd/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_solution_biao\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','47','1','0','ganyanbingdujiance','');
INSERT INTO `bc_category` VALUES('48','1','content','0','1','47','0,4,47','0','48','方案介绍','','/uploadfile/2021/1130/20211130053620115.png','','solution/gybd/','fajs','/index.php?m=content&c=index&a=lists&catid=48','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','fanganjieshao','');
INSERT INTO `bc_category` VALUES('49','1','content','0','1','47','0,4,47','0','49','图片说明','','/uploadfile/2021/1130/20211130053620115.png','','solution/gybd/','tpsm','/index.php?m=content&c=index&a=lists&catid=49','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','tupianshuoming','');
INSERT INTO `bc_category` VALUES('50','1','content','0','22','47','0,4,47','0','50','检测项目','','/uploadfile/2021/1130/20211130053620115.png','','solution/gybd/','jcxm','/index.php?m=content&c=index&a=lists&catid=50','9','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','jiancexiangmu','');
INSERT INTO `bc_category` VALUES('51','1','content','0','1','4','0,4','1','51,52,53,54','肠道病毒检测','','/uploadfile/2021/1130/20211130054253296.png','','solution/','cdbd','/index.php?m=content&c=index&a=lists&catid=51','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_solution_biao\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','51','1','0','changdaobingdujiance','');
INSERT INTO `bc_category` VALUES('52','1','content','0','1','51','0,4,51','0','52','方案介绍','','/uploadfile/2021/1130/20211130054253296.png','','solution/cdbd/','fajs','/index.php?m=content&c=index&a=lists&catid=52','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','fanganjieshao','');
INSERT INTO `bc_category` VALUES('53','1','content','0','1','51','0,4,51','0','53','图片说明','','/uploadfile/2021/1130/20211130054253296.png','','solution/cdbd/','tpsm','/index.php?m=content&c=index&a=lists&catid=53','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','tupianshuoming','');
INSERT INTO `bc_category` VALUES('54','1','content','0','22','51','0,4,51','0','54','检测项目','','/uploadfile/2021/1130/20211130054253296.png','','solution/cdbd/','jcxm','/index.php?m=content&c=index&a=lists&catid=54','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','jiancexiangmu','');
INSERT INTO `bc_category` VALUES('55','1','content','0','1','5','0,5','1','55,56,57','服务体系','','/uploadfile/2021/1130/20211130084026552.png','','support/','servers','/support/servers/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_support\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','55','1','0','fuwutixi','');
INSERT INTO `bc_category` VALUES('56','1','content','0','1','55','0,5,55','0','56','体系介绍','','/uploadfile/2021/1130/20211130084026552.png','','support/servers/','txjs','/index.php?m=content&c=index&a=lists&catid=56','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','tixijieshao','');
INSERT INTO `bc_category` VALUES('57','1','content','0','1','55','0,5,55','0','57','服务项目','','/uploadfile/2021/1130/20211130084026552.png','','support/servers/','fwxm','/index.php?m=content&c=index&a=lists&catid=57','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','fuwuxiangmu','');
INSERT INTO `bc_category` VALUES('58','1','content','0','29','5','0,5','1','58,59,60,61,62,63,64','业务联系','','/uploadfile/2021/1130/20211130090935542.png','','support/','ywlx','/support/ywlx/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_support_catcont\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','58','1','0','yewulianxi','');
INSERT INTO `bc_category` VALUES('59','1','content','0','29','58','0,5,58','0','59','华北','','','','support/ywlx/','hb','/index.php?m=content&c=index&a=lists&catid=59','7','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','59','1','0','huabei','');
INSERT INTO `bc_category` VALUES('60','1','content','0','29','58','0,5,58','0','60','西北','','','','support/ywlx/','xb','/index.php?m=content&c=index&a=lists&catid=60','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','60','1','0','xibei','');
INSERT INTO `bc_category` VALUES('61','1','content','0','29','58','0,5,58','0','61','西南','','','','support/ywlx/','xn','/index.php?m=content&c=index&a=lists&catid=61','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','61','1','0','xinan','');
INSERT INTO `bc_category` VALUES('62','1','content','0','29','58','0,5,58','0','62','华东','','','','support/ywlx/','hd','/index.php?m=content&c=index&a=lists&catid=62','6','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','62','1','0','huadong','');
INSERT INTO `bc_category` VALUES('63','1','content','0','29','58','0,5,58','0','63','华中','','','','support/ywlx/','hz','/index.php?m=content&c=index&a=lists&catid=63','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','63','1','0','huazhong','');
INSERT INTO `bc_category` VALUES('64','1','content','0','29','58','0,5,58','0','64','华南','','','','support/ywlx/','hn','/index.php?m=content&c=index&a=lists&catid=64','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','64','1','0','huanan','');
INSERT INTO `bc_category` VALUES('65','1','content','0','2','5','0,5','0','65','常见问题','','/uploadfile/2021/1130/20211130113957479.png','','support/','cjwt','/support/cjwt/','16','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_support\',
  \'show_template\' => \'show_news\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','65','1','0','changjianwenti','');
INSERT INTO `bc_category` VALUES('66','1','content','0','1','6','0,6','0','66','公司理念','','/uploadfile/2021/1130/20211130115843271.png','','join/','rcln','/index.php?m=content&c=index&a=lists&catid=66','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_join\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','gongsilinian','');
INSERT INTO `bc_category` VALUES('67','1','content','0','1','6','0,6','1','67,68,69','员工福利','','/uploadfile/2021/1201/20211201122331741.png','','join/','ygfl','/index.php?m=content&c=index&a=lists&catid=67','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_join\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','yuangongfuli','');
INSERT INTO `bc_category` VALUES('68','1','content','0','1','67','0,6,67','0','68','精彩图片','','/uploadfile/2021/1201/20211201122331741.png','','join/ygfl/','jctp','/index.php?m=content&c=index&a=lists&catid=68','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','jingcaitupian','');
INSERT INTO `bc_category` VALUES('69','1','content','0','1','67','0,6,67','0','69','福利项目','','/uploadfile/2021/1201/20211201122331741.png','','join/ygfl/','flxm','/index.php?m=content&c=index&a=lists&catid=69','6','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','fulixiangmu','');
INSERT INTO `bc_category` VALUES('70','1','content','0','21','6','0,6','0','70','招聘信息','','/uploadfile/2021/1201/20211201010733229.png','','join/','hr','/index.php?m=content&c=index&a=lists&catid=70','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_join_hr\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','zhaopinxinxi','');
INSERT INTO `bc_category` VALUES('71','1','content','0','30','3','0,3','1','71,73,74,92,93,94,95,96,97','试剂平台','','/uploadfile/2021/1202/20211202064510331.png','','product/','platform','/product/platform/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_product_all\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','71','1','0','shijipingtai','');
INSERT INTO `bc_category` VALUES('72','1','content','0','31','3','0,3','1','72,75,76,77','设备','','/uploadfile/2021/1202/20211202064538467.png','','product/','equipment','/product/equipment/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_product_all\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','72','1','0','shebei','');
INSERT INTO `bc_category` VALUES('78','1','content','0','1','0','0','1','78,79,80,81,82,83,84,85,86,87,98,88,89,90','首页布局','','','','','inbj','/inbj/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','78','0','0','shouyebuju','');
INSERT INTO `bc_category` VALUES('73','1','content','0','30','71','0,3,71','0','73','胶体金-呼吸道','','','','product/platform/','hxd','/product/platform/hxd/','16','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','1','1','0','jiaotijin-huxidao','');
INSERT INTO `bc_category` VALUES('74','1','content','0','30','71','0,3,71','0','74','胶体金-优生','','','','product/platform/','ys','/product/platform/ys/','12','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','2','1','0','jiaotijin-yousheng','');
INSERT INTO `bc_category` VALUES('75','1','content','0','31','72','0,3,72','0','75','胶体金仪器','','/uploadfile/2021/1202/20211202064538467.png','','product/equipment/','jtj','/product/equipment/jtj/','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_device\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','75','1','0','jiaotijinyiqi','');
INSERT INTO `bc_category` VALUES('76','1','content','0','31','72','0,3,72','0','76','英诺特呼吸道九联检','','/uploadfile/2021/1130/20211130084026552.png','','product/equipment/','jlq','/product/equipment/jlq/','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_device_03\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','76','1','0','yingnuotehuxidaojiulianjian','');
INSERT INTO `bc_category` VALUES('77','1','content','0','31','72','0,3,72','0','77','核酸提取仪','','/uploadfile/2021/1202/20211202064538467.png','','product/equipment/','hstq','/product/equipment/hstq/','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_device_02\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','77','1','0','hesuantiquyi','');
INSERT INTO `bc_category` VALUES('79','1','content','0','1','78','0,78','0','79','banner管理','','','','inbj/','banner','/index.php?m=content&c=index&a=lists&catid=79','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','79','1','0','bannerguanli','');
INSERT INTO `bc_category` VALUES('80','1','content','0','1','78','0,78','0','80','我们的产品','','','','inbj/','cpgl','/index.php?m=content&c=index&a=lists&catid=80','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','80','1','0','womendechanpin','');
INSERT INTO `bc_category` VALUES('81','1','content','0','1','78','0,78','0','81','解决方案','','','','inbj/','jjfa','/index.php?m=content&c=index&a=lists&catid=81','6','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','81','1','0','jiejuefangan','');
INSERT INTO `bc_category` VALUES('82','1','content','0','1','78','0,78','1','82,83,84,85','了解英诺特','','','','inbj/','ljynt','/index.php?m=content&c=index&a=lists&catid=82','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','82','1','0','liaojieyingnuote','');
INSERT INTO `bc_category` VALUES('83','1','content','0','1','82','0,78,82','0','83','关于介绍','','','','inbj/ljynt/','gyjs','/index.php?m=content&c=index&a=lists&catid=83','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','83','1','0','guanyujieshao','');
INSERT INTO `bc_category` VALUES('84','1','content','0','1','82','0,78,82','0','84','动态数据','','','','inbj/ljynt/','dtsj','/index.php?m=content&c=index&a=lists&catid=84','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','84','1','0','dongtaishuju','');
INSERT INTO `bc_category` VALUES('85','1','content','0','1','82','0,78,82','0','85','企业视频','','','','inbj/ljynt/','qysp','/index.php?m=content&c=index&a=lists&catid=85','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','85','1','0','qiyeshipin','');
INSERT INTO `bc_category` VALUES('86','1','content','0','1','78','0,78','1','86,87,98,88,89,90','底部管理','','','','inbj/','dbgl','/inbj/dbgl/','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','86','1','0','dibuguanli','');
INSERT INTO `bc_category` VALUES('87','1','content','0','1','86','0,78,86','0','87','二维码管理','','','','inbj/dbgl/','ewmgl','/index.php?m=content&c=index&a=lists&catid=87','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','1','1','0','erweimaguanli','');
INSERT INTO `bc_category` VALUES('88','1','content','0','1','86','0,78,86','0','88','链接管理','','','','inbj/dbgl/','ljgl','/index.php?m=content&c=index&a=lists&catid=88','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show_low\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','lianjieguanli','');
INSERT INTO `bc_category` VALUES('89','1','content','0','1','86','0,78,86','0','89','版权信息','','','','inbj/dbgl/','bqxx','/index.php?m=content&c=index&a=lists&catid=89','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','4','1','0','banquanxinxi','');
INSERT INTO `bc_category` VALUES('90','1','content','0','1','86','0,78,86','0','90','备案管理','','','','inbj/dbgl/','icpgl','/index.php?m=content&c=index&a=lists&catid=90','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','5','1','0','beianguanli','');
INSERT INTO `bc_category` VALUES('93','1','content','0','30','71','0,3,71','0','93','酶免-呼吸道','','/uploadfile/2021/1202/20211202064510331.png','','product/platform/','hxds','/product/platform/hxds/','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','4','1','0','meimian-huxidao','');
INSERT INTO `bc_category` VALUES('94','1','content','0','30','71','0,3,71','0','94','酶免-优生','','/uploadfile/2021/1202/20211202064510331.png','','product/platform/','yss','/product/platform/yss/','10','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','5','1','0','meimian-yousheng','');
INSERT INTO `bc_category` VALUES('95','1','content','0','30','71','0,3,71','0','95','酶免-肝炎','','/uploadfile/2021/1202/20211202064510331.png','','product/platform/','mmgy','/product/platform/mmgy/','7','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','6','1','0','meimian-ganyan','');
INSERT INTO `bc_category` VALUES('96','1','content','0','30','71','0,3,71','0','96','酶免-肠道','','/uploadfile/2021/1202/20211202064510331.png','','product/platform/','mmcd','/product/platform/mmcd/','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','7','1','0','meimian-changdao','');
INSERT INTO `bc_category` VALUES('97','1','content','0','30','71','0,3,71','0','97','荧光-呼吸道','','/uploadfile/2021/1202/20211202064510331.png','','product/platform/','yghxds','/product/platform/yghxds/','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'1\',
  \'content_ishtml\' => \'1\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_product\',
  \'show_template\' => \'show_product\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'11\',
)','8','1','0','yingguang-huxidao','');
INSERT INTO `bc_category` VALUES('98','1','content','0','1','86','0,78,86','0','98','底部联系方式','','','','inbj/dbgl/','dblx','/index.php?m=content&c=index&a=lists&catid=98','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','dibulianxifangshi','');
