<?php
return array (
  'top_name' => 
  array (
    'fieldid' => '333',
    'modelid' => '23',
    'siteid' => '1',
    'field' => 'top_name',
    'name' => '姓名',
    'tips' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '8',
    'pattern' => '',
    'errortips' => '请正确的名字',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'top_tel' => 
  array (
    'fieldid' => '334',
    'modelid' => '23',
    'siteid' => '1',
    'field' => 'top_tel',
    'name' => '联系方式',
    'tips' => '请填写11位正确的手机号码',
    'css' => '',
    'minlength' => '11',
    'maxlength' => '11',
    'pattern' => '/^[0-9.-]+$/',
    'errortips' => '您填写的手机号码不正确',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'top_mail' => 
  array (
    'fieldid' => '335',
    'modelid' => '23',
    'siteid' => '1',
    'field' => 'top_mail',
    'name' => '邮箱',
    'tips' => '请填写正确的邮箱地址',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^[\\w\\-\\.]+@[\\w\\-\\.]+(\\.\\w+)+$/',
    'errortips' => '您填写的邮箱格式不正确',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '3',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'top_nr' => 
  array (
    'fieldid' => '336',
    'modelid' => '23',
    'siteid' => '1',
    'field' => 'top_nr',
    'name' => '留言内容',
    'tips' => '请填写100字的内容描述',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '200',
    'pattern' => '',
    'errortips' => '您填写正确的内容信息',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'100%\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '4',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
);
?>